<?xml version="1.0"?>
<robot name="ridgeback_yumi" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ridgeback_description)/urdf/ridgeback.urdf.xacro" />



  <!-- Import Rviz colors -->
  <xacro:include filename="$(find yumi_description)/urdf/Util/materials.xacro" />
  <!-- Import utilities -->
  <xacro:include filename="$(find yumi_description)/urdf/Util/utilities.xacro" />
  <!--Import the yumi macro -->
  <xacro:include filename="$(find yumi_description)/urdf/yumi.xacro"/>
  <!--Import the yumi servo gripper macro -->
  <xacro:include filename="$(find yumi_description)/urdf/Grippers/yumi_servo_gripper.xacro"/>
  <!--Import the yumi optodaq sensors macro -->
  <xacro:include filename="$(find yumi_description)/urdf/Extras/yumi_optodaq_sensors.xacro"/>
  <!-- Import Gazebo plugins -->
  <xacro:include filename="$(find yumi_description)/urdf/Gazebo/gazebo.urdf.xacro"/>


  <!--yumi-->
  <xacro:yumi name="yumi" hardware_interface="hardware_interface/VelocityJointInterface" parent="yumi_pedestal">
    <origin xyz="0 0 0.1" rpy="0 0 0" />
  </xacro:yumi>


  <xacro:yumi_optodaq_sensor name="optodaq_r" parent="yumi_link_7_r">
      <origin xyz="0 0 0.033" rpy="0 ${PI} ${-PI/4}" />
  </xacro:yumi_optodaq_sensor>

  <xacro:yumi_optodaq_sensor name="optodaq_l" parent="yumi_link_7_l">
	  <origin xyz="0 0 0.033" rpy="0 ${PI} ${-PI/4}" />
  </xacro:yumi_optodaq_sensor>

  <!--right gripper-->
  <xacro:yumi_servo_gripper name="gripper_r" hardware_interface="hardware_interface/EffortJointInterface" parent="optodaq_r_sensor_link">
    <origin xyz="0 0 -0.033" rpy="${PI} 0.0 ${PI/4}" />
  </xacro:yumi_servo_gripper>

  <!--left gripper-->
  <xacro:yumi_servo_gripper name="gripper_l" hardware_interface="hardware_interface/EffortJointInterface" parent="optodaq_l_sensor_link">
    <origin xyz="0 0 -0.033" rpy="${PI} 0.0 ${PI/4}" />
  </xacro:yumi_servo_gripper>


  <xacro:property name="pedestal_height" value="0.28" />
  <xacro:property name="pedestal_offset_x" value="0.32" />
  <xacro:property name="yumi_offset_x" value="0.06" />
  <xacro:property name="yumi_height" value="0.25" />
  <!-- Constants for Intel d435 mount dimensions -->
  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="0.5" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.065" /> <!-- Radius of the camera mount -->
  <xacro:property name="height" value="0.4" /> <!--Height of the camera mount -->
  <xacro:property name="camera_length" value="0.09" /> <!-- Size of square 'camera' box -->
  <xacro:property name="camera_width" value="0.025" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="angle_diff" value="${pi/3}" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="angle_tilt_1" value="${pi/6}" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="angle_tilt_2" value="${pi/36}" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="angle_tilt_3" value="${pi/36}" /> <!-- Space btw top of beam and the each joint -->

  <joint name="ridgeback_base_to_pedestal" type="fixed">
    <origin rpy="0 0 ${PI}" xyz="${pedestal_offset_x} 0 ${pedestal_height}" />
    <parent link="base_link" />
    <child link="yumi_pedestal" />
  </joint>

  <link name="yumi_pedestal">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${PI}" />
      <geometry>
        <mesh filename="package://ridgeback_yumi_description/meshes/IRB14000_mount.stl"/>
      </geometry>
      <material name="black" />
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${PI}" />
      <geometry>
        <mesh filename="package://ridgeback_yumi_description/meshes/IRB14000_mount.stl"/>
      </geometry>
      <material name="black" />
    </visual>
  </link>


  <joint name="pedestal_to_yumi" type="fixed">
    <origin rpy="0 0 ${PI}" xyz="${yumi_offset_x} 0 ${yumi_height}" />
    <parent link="yumi_pedestal" />
    <child link="yumi_base_link" />
  </joint>


  <xacro:include filename="$(find multi_d435_description)/urdf/multi_d435.gazebo" />
  
  <joint name="yumi_to_mount" type="fixed">
    <parent link="yumi_base_link" />
    <child link="multi_d435_mount" />
    <origin rpy="0 0 0" xyz="-0.05 0 0.4" />
  </joint>


  <!-- Camera mount Link -->
  <link name="multi_d435_mount">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
         <cylinder radius="${width}" length="${height}"/>
      </geometry>
    </collision>

   <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi/6}"/>
      <geometry>
	       <mesh scale= "0.007 0.007 0.01" filename="package://multi_d435_description/meshes/d435_mount.dae"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="camera_joint_1" type="fixed">
    <origin xyz="${width+camera_width} 0 ${height-camera_length}" rpy="0 ${angle_tilt_1} 0"/>
    <parent link="multi_d435_mount"/>
    <child link="camera_link_1"/>
  </joint>

  <joint name="camera_joint_2" type="fixed">
    <origin xyz="${(width+camera_width)*cos(angle_diff)} ${(width+camera_width)*sin(angle_diff)} ${height-camera_length}" rpy="0 ${angle_tilt_2} ${angle_diff}"/>
    <parent link="multi_d435_mount"/>
    <child link="camera_link_2"/>
  </joint>

  <joint name="camera_joint_3" type="fixed">
    <origin xyz="${(width+camera_width)*cos(angle_diff)} -${(width+camera_width)*sin(angle_diff)} ${height-camera_length}" rpy="0 ${angle_tilt_3} -${angle_diff}"/>
    <parent link="multi_d435_mount"/>
    <child link="camera_link_3"/>
  </joint>


  <!-- Camera 1-->
  <link name="camera_link_1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	       <box size="${camera_length} ${camera_width} ${camera_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} ${pi/2}"/>
      <geometry>
	       <mesh filename="package://multi_d435_description/meshes/d435.dae"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="0.0615752" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="9.108e-05" ixy="0" ixz="0" iyy="2.51e-06" iyz="0" izz="8.931e-05" />
    </inertial>
  </link>

  <!-- Camera 2-->
  <link name="camera_link_2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	       <box size="${camera_length} ${camera_width} ${camera_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} ${pi/2}"/>
      <geometry>
	       <mesh filename="package://multi_d435_description/meshes/d435.dae"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="0.0615752" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="9.108e-05" ixy="0" ixz="0" iyy="2.51e-06" iyz="0" izz="8.931e-05" />
    </inertial>
  </link>

  <!-- Camera 3-->
  <link name="camera_link_3">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	       <box size="${camera_length} ${camera_width} ${camera_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} ${pi/2}"/>
      <geometry>
	       <mesh filename="package://multi_d435_description/meshes/d435.dae"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.0615752" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="9.108e-05" ixy="0" ixz="0" iyy="2.51e-06" iyz="0" izz="8.931e-05" />
    </inertial>
  </link>

  <joint name="camera_optical_joint_1" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link_1"/>
    <child link="camera_link_optical_1"/>
  </joint>

  <link name="camera_link_optical_1">
  </link>

  <joint name="camera_optical_joint_2" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link_2"/>
    <child link="camera_link_optical_2"/>
  </joint>

  <link name="camera_link_optical_2">
  </link>

  <joint name="camera_optical_joint_3" type="fixed">
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link_3"/>
    <child link="camera_link_optical_3"/>
  </joint>

  <link name="camera_link_optical_3">
  </link>

</robot>
